name: Create .ZIP release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  deployzip:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Setup enviroment
        run: |
          VERSION="${{ github.ref_name }}"
          SUBMISSION_ID=$(echo ${{ vars.SUBMISSION }} | sed 's/-.*$//')
          RELEASE_NAME=$(echo ${{ vars.SUBMISSION }} | sed 's/^.*-//')
          ZIP_NAME=${{ secrets.STUDENTID }}-$RELEASE_NAME.zip
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "SUBMISSION_ID=$SUBMISSION_ID" >> $GITHUB_ENV
          echo "RELEASE_NAME=$RELEASE_NAME" >> $GITHUB_ENV
          echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create zip
        run: bash create_zip.sh "$ZIP_NAME"
      - name: Upload zip
        run: bash moodle-upload.sh "${{ secrets.MOODLE_NAME }}" "${{ secrets.MOODLE_PW }}" "$SUBMISSION_ID" "$ZIP_NAME"
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: RELEASE-${{ env.VERSION }}
          prerelease: false
          draft: false
          files: |
            ${{ env.ZIP_NAME }}

